// 改动说明：SOP使用真实腾讯地图与明确样本地址，只读取地图allowlist配置，不复制业务库和其它密钥。
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
export const GEO_FIXTURE=Object.freeze({provider:'tencent',address:'杭州市西湖区浙江大学紫金港校区'});
export const MAP_SECRET_KEYS=['HYACINTHUS_GEO__TENCENT_API_KEY','HYACINTHUS_GEO__FRONTEND_CANDIDATES__TENCENT__BROWSER_API_KEY'];
/** Read exactly the two required map credentials and construct isolated typed runtime defaults. */
export async function mapEnvironment(repo){const file=process.env.HYACINTHUS_E2E_MAP_ENV_FILE||path.join(repo,'.env.runtime');const config={HYACINTHUS_GEO__ENABLED:'true',HYACINTHUS_GEO__GEOCODE_PROVIDER_ORDER:'tencent',HYACINTHUS_GEO__REVERSE_PROVIDER_ORDER:'tencent',HYACINTHUS_GEO__FRONTEND_PROVIDER_ORDER:'tencent',HYACINTHUS_GEO__FRONTEND_CANDIDATES__TENCENT__RENDER_ENGINE:'tencent_gl'};for(const line of (await readFile(file,'utf8')).split(/\r?\n/)){const i=line.indexOf('=');if(i<0)continue;const key=line.slice(0,i).trim();if(!MAP_SECRET_KEYS.includes(key))continue;const raw=line.slice(i+1).trim();config[key]=raw.replace(/^(["'])(.*)\1$/,'$2');}for(const key of MAP_SECRET_KEYS)assert.ok(config[key],`Real map fixture needs configured ${key}`);return config;}
/** Probe a real public provider and persist only the location and status, never its request URL/key. */
export async function probeMap(config){let response;try{const url=new URL('https://apis.map.qq.com/ws/geocoder/v1/');url.searchParams.set('address',GEO_FIXTURE.address);url.searchParams.set('key',config.HYACINTHUS_GEO__TENCENT_API_KEY);response=await fetch(url,{signal:AbortSignal.timeout(20_000)});}catch(error){throw new Error(`Real Tencent map probe failed (${error.name})`);}assert.equal(response.status,200,'Real map HTTP request failed');const data=await response.json();assert.equal(data.status,0,`Real Tencent map returned status ${data.status}`);const location=data.result?.location;assert.ok(Number.isFinite(location?.lng)&&Number.isFinite(location?.lat),'Real map returned no location');return {...GEO_FIXTURE,realProvider:true,providerStatus:0,location};}
/** Verify the running Rust API's actual geo adapter, including its container transport and policy. */
export async function probeBackendMap(api){const url=new URL(`${api}/api/v1/geo/geocode`);url.searchParams.set('address',GEO_FIXTURE.address);url.searchParams.set('city','杭州');const response=await fetch(url,{signal:AbortSignal.timeout(20_000)});const data=await response.json();assert.equal(response.status,200,`Actual backend map probe HTTP ${response.status}`);assert.equal(data.code,0,'Actual backend map probe failed');assert.ok(Number.isFinite(data.data?.lng)&&Number.isFinite(data.data?.lat),'Actual backend geocoder returned no coordinates');return {...GEO_FIXTURE,actualBackend:true,status:response.status,response:data.data};}
/** Replace only copied map fields in an existing private test environment; unrelated runtime settings stay intact. */
export function withoutMapSecrets(text){return text.split('\n').filter(line=>!MAP_SECRET_KEYS.includes(line.split('=',1)[0])).join('\n');}
