// 改动说明：用真实逐例证据生成大白话HTML，展示来源字段、负例、历史失败及桌面/手机验收。
import assert from 'node:assert/strict';
import { writeFile, readFile, mkdir, readdir, copyFile } from 'node:fs/promises';
import path from 'node:path';
import { chromium } from 'playwright';
const labels={passed:'通过',failed:'失败',blocked:'依赖阻塞',not_run:'未运行'};
const types={engineering:'容器工程检查',pi:'真实 Pi',mixed:'真实 Pi＋协议检查',host:'宿主检查'};
const descriptions={A1:'正式安装器导出到自动识别、指定Pi和相对目录，逐文件与内嵌内容比较。',A2:'用登记过的旧安装状态升级，检查自建文件保留和引用损坏报警。',A3:'实际禁止socket/connect后仍可读取正文，坏配置也不影响发现。',B1:'只给自然语言任务，看默认Pi是否发现并阅读入口。',B2:'真实doctor检查健康实例，再检查CLI网络不可达是否失败。',B3:'用原始授权链接批准，继续同一申请；合法空结果结束。',C1:'批准前独立回读原值，批准后回读新显示名。',C2:'批准前规则不存在，批准后只生成一条前缀规则；D3检查实际命中。',D1:'不给来源时先询问；给保存邮件后检查原始字节、哈希、30条顺序、规范字段和联系方式归属。',D2:'读取真实API/Worker解析及完整dry-run请求，与原邮件逐字段比较；v3另做20字段联系角色工程探测。',D3:'批准前0条，批准后真实创建30条；独立管理员回读全部详情。',D4:'同容器新会话重放同一邮件，30个ID和首次报告保持不变。',E1:'分别检查拒绝授权、歧义、旧批准、未知回执、明确失败恢复及online缺地址拒绝。',E2:'撤销本轮授权、删除临时模型凭据、停止Pi、移除地图凭据副本与API/Worker容器并扫描公开证据。'};
/** Escape all observations, including untrusted model replies, as HTML text. */
function escape(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
/** Read optional historical evidence without claiming it exists or passed. */
async function optionalJson(file,fallback){try{return JSON.parse(await readFile(file,'utf8'));}catch(e){if(e.code==='ENOENT')return fallback;throw e;}}
/** Summarize terminal history; no previous success substitutes for the current round. */
async function historyBefore(output){const parent=path.dirname(output);const list=[];for(const name of await readdir(parent)){if(!/^SOP\d+$/.test(name)||name>=path.basename(output))continue;const value=await optionalJson(path.join(parent,name,'result.json'),null);if(!value)continue;list.push({runId:name,kind:value.kind||'未记录',sopVersion:value.sopVersion||'未记录',status:value.status||'未结束',passed:value.cases.filter(c=>c.status==='passed').map(c=>c.id),failed:value.cases.filter(c=>c.status==='failed').map(c=>({id:c.id,reason:c.reason})),cancelled:value.cancellationReason||value.failure||value.manualCleanup?.reason||'',manualCleanup:Boolean(value.manualCleanup),report:path.join(parent,name,'report.html'),result:path.join(parent,name,'result.json')});}return list;}
/** Archive actual regression logs and compute counts from their observed terminal lines. */
async function regressionEvidence(output){const entries=[];const sources=[['CLI Rust回归','/tmp/hyacinthus-sop-cli-tests.log','rust'],['测试器 Node 回归','/tmp/hyacinthus-sop-node-tests.log','node'],['npm安装器回归','/tmp/hyacinthus-sop-installer-tests.log','node'],['CLI Clippy，job=1','/tmp/hyacinthus-sop-cli-clippy-job1.log','clippy'],['Backend受保护脚本Clippy','/tmp/hyacinthus-sop-backend-clippy.log','clippy']];await mkdir(path.join(output,'regressions'),{recursive:true});for(const [name,file,kind]of sources){try{const text=await readFile(file,'utf8');const target=`regressions/${path.basename(file)}`;await copyFile(file,path.join(output,target));let state='没有完整结束证据';if(kind==='rust'){const matches=[...text.matchAll(/test result: ok\. (\d+) passed; (\d+) failed/g)];if(matches.length)state=`${matches.reduce((n,m)=>n+Number(m[1]),0)}通过，${matches.reduce((n,m)=>n+Number(m[2]),0)}失败`;}else if(kind==='node'){const pass=text.match(/^(?:#|ℹ) pass (\d+)$/m),fail=text.match(/^(?:#|ℹ) fail (\d+)$/m);if(pass&&fail)state=`${pass[1]}通过，${fail[1]}失败`;}else if(/Finished .*profile/.test(text)&&!/^error:/m.test(text))state='已完成，无编译检查错误';entries.push({name,state,path:target});}catch(e){if(e.code!=='ENOENT')throw e;}}await writeFile(path.join(output,'regressions/index.json'),JSON.stringify(entries,null,2));return entries;}
/** Render a self-contained explanation using only the supplied observed case states. */
export function renderSopHtml(result,{history=[],regressions=[],output=''}={}){
 const recoveryCount=result.cases.find(c=>c.id==='E1')?.subcases?.length||5;const version2=['sop-v2','sop-v3'].includes(result.sopVersion);const normalizedCount=result.sopVersion==='sop-v3'?20:16;const passed=result.cases.filter(c=>c.status==='passed').length;const full=result.kind==='full';const d3=result.cases.find(c=>c.id==='D3');const fieldStatus=d3?.status==='passed'?'30条全部匹配':'未取得本轮完整通过证据';
 const parseSummary=result.cases.find(c=>c.id==='D2')?.actual?.parserOriginalSummary;
 const parserAttempts=result.cases.find(c=>c.id==='D2')?.actual?.parserAttempts||[];
 const fields=[['编号与顺序','本轮前缀-001 至 -030，30个唯一ID'],['业务类型与方式','tutoring，online；当前契约同样要求地址与有效定位'],['地址及定位',version2?'杭州市西湖区浙江大学紫金港校区；真实地图服务与后端取得定位':'历史样本只有线上、无线下地点（不符合现行契约）'],['年级、科目','初一、数学；使用现有目录ID'],['发布方与学生','家长发布、男学生'],['老师条件','女老师、本科；经验保留在描述，未给职业身份则为null'],['薪酬及单位','第1～30条分别100～129元/小时'],['频率、时长','每周1次，每次120分钟，上下限都保留'],['时间段','周六14:00～16:00'],['用户联系方式','原邮件未给，电话/微信留空，不借用管理员电话'],['管理员联系方式','管理员电话13800138000，存ext.admin_contact_phone；管理员微信未给留空'],['规则实际命中','全部优先级5']];
 const link=(href,label)=>`<a href="${escape(href)}">${escape(label)}</a>`;const evidence=(id,file,label=file)=>link(`cases/${id}/${file}`,label);
 const subcases=result.cases.find(c=>c.id==='E1')?.actual?.subcases||[];
 return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>同容器 SOP 实测结果</title><style>*{box-sizing:border-box}body{margin:0;background:#f3f6f5;color:#17332d;font:16px/1.8 system-ui,sans-serif;overflow-wrap:anywhere}main{max-width:1080px;margin:auto;padding:30px 20px}header{background:#1b493f;color:white;padding:28px;border-radius:16px}section{background:white;border:1px solid #dce7e2;border-radius:12px;padding:24px;margin:22px 0}h1{line-height:1.4}h2{font-size:23px}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f4f7f5;padding:15px;font-size:13px}a{color:#246e58}table{width:100%;border-collapse:collapse;text-align:left;font-size:14px}td,th{padding:12px;border-bottom:1px solid #dae4df;vertical-align:top}.table{overflow:auto}details{margin:18px 0}summary{cursor:pointer;font-weight:bold}li{margin:8px 0}.badge{display:inline-block;padding:3px 10px;background:#e6f2ec;border-radius:6px;font-weight:bold}@media(max-width:700px){main{padding:15px 12px}header,section{padding:20px 16px}table{min-width:660px}}</style></head><body><main>
 <header><p>真实 Pi / MiMo · 标准化 SOP（${escape(result.sopVersion||'未记录版本')}） · 同一个 Pi＋CLI 容器</p><h1>${full?'完整':'专项'}实测：${labels[result.status]||escape(result.status)}</h1><p>本轮 ${passed}/${result.cases.length} 项通过。失败、依赖阻塞和未运行都按实际记录。</p><p>${escape(result.runId)} · ${escape(result.model)}<br>${escape(result.startedAt)} 至 ${escape(result.endedAt)} · ${Math.round(result.durationMs/1000)}秒</p></header>
 <section><h2>1. 我理解的任务</h2><p>让Agent看到普通用户请求，就能发现这个CLI、读需要的指南、处理授权，并完成任务。两套测试合并使用同一个Pi＋CLI容器；API、Worker和数据库仍是各自的服务容器。不同任务可以开不同会话，邮件重放只保留这封邮件的工作目录和profile。</p><p>验证要看到真实业务结果：读过技能、实际调用CLI、真实授权、先预览再确认、确实落库、独立回读、重复处理没有多写。静态文件检查和单元测试都有用，但不能替代这些证据。</p></section>
 <section><h2>2. 对齐 lark-cli 后改了什么</h2><p>实际参考仓库：/tmp/hyacinthus-lark-cli-reference，v1.0.97，<a href="https://github.com/larksuite/cli/tree/7beffb086d7fa3c5b843d8affa7c089f49cfc65e">固定提交7beffb0</a>。</p><div class="table"><table><thead><tr><th>Agent需要什么</th><th>这次实现</th></tr></thead><tbody><tr><td>安装后能发现</td><td>正式安装步骤识别已有Agent目录，也支持指定Pi和相对目录。npm包没有postinstall自动安装Skills；调用install步骤才导出。</td></tr><tr><td>入口简短，细节按需读</td><td>收口为hyacinthus-cli和邮件上传两个入口，11篇引用；旧系列中有效业务规则进入引用，不继续堆多个重复入口。</td></tr><tr><td>没登录也能认识CLI</td><td>Skills内嵌在二进制；list/read/export/check支持离线发现，坏profile不阻塞读取。</td></tr><tr><td>实际流程合理</td><td>本轮整理规范为${normalizedCount}字段；v3将授课方式、用户联系方式、管理员电话/微信列为独立字段，联系方式不放备注。保留相对任务目录、原邮件和来源哈希；只申请本任务权限；访问授权和业务确认分开；查询摘要不能充当完整详情；邮件与优先级规则dry-run可保存完整预览文件。</td></tr><tr><td>一次测试可复用</td><td>统一版本清单、默认Docker入口、确认规则、14项操作卡、${recoveryCount}个恢复负例、结果与清理流程。</td></tr></tbody></table></div><p>A1验证的是本地正式安装器导出。发布下载链路未在本轮验证，不把它写成已通过。</p><details><summary>旧系列怎样整合</summary><ul><li>hyacinthus-shared：授权、权限、确认及输出风险进入auth.md、shared.md、output-risk.md。</li><li>hyacinthus-agent-runtime：发现、能力导航与按需读取进入CLI主入口和capability-map.md。</li><li>hyacinthus-requirements：整理、解析、导入、查询、目录和规则拆成requirements-*、catalog.md、priority-rules.md、batch-and-geo.md。</li><li>邮件上传保留独立入口：负责来源、相对目录、用户补充、稳定键、报告与重复处理，再引用通用CLI指南。</li></ul><p>升级只清理旧安装清单登记的文件，自建文件继续保留；A2验证了这一点。</p></details></section>
 <section><h2>3. 用什么验证，实际结果怎样</h2><div class="table"><table><thead><tr><th>用例</th><th>方法</th><th>结果／秒</th><th>检查和证据</th></tr></thead><tbody>${result.cases.map(c=>`<tr><td>${escape(c.id)} ${escape(c.name)}</td><td>${escape(types[c.type]||c.type)}</td><td><span class="badge">${labels[c.status]||escape(c.status)}</span><br>${c.duration_ms?Math.round(c.duration_ms/1000):'—'}</td><td>${escape(descriptions[c.id]||'')} ${c.reason?`<p>实际失败：${escape(c.reason)}</p>`:''}<br>${evidence(c.id,'case.json','用例原始记录')} · ${c.type==='pi'||c.type==='mixed'?evidence(['D2','D3'].includes(c.id)?'D1':c.id,c.id==='E1'?'subcases.json':'conversation.json',c.id==='E1'?`${recoveryCount}个负例`:'Pi对话'):evidence(c.id,c.id==='A1'?'installer.json':c.id==='A2'?'upgrade.json':c.id==='A3'?'offline.json':'revocations.json','验证证据')}</td></tr>`).join('')}</tbody></table></div><p>D1～D3是同一个真实业务会话的分阶段检查，D4是新会话。每例开始和结束都核对容器、CLI及Skills哈希。</p>${link('result.json','完整结果与证据索引')}</section>
 <section><h2>4. 30条岗位逐字段核对</h2>${parserAttempts.length?`<p>实际解析${parserAttempts.length}次：首次成功${escape(parserAttempts[0].summary.success)}条、失败${escape(parserAttempts[0].summary.failed)}条，错误为${escape(parserAttempts[0].errorCodes.join('、')||'无')}；最后一次成功${escape(parserAttempts.at(-1).summary.success)}条、失败${escape(parserAttempts.at(-1).summary.failed)}条。${evidence('D2','parser-attempts.json','每次解析记录')}。首次有错误时，是Agent按原邮件修正后再解析；本轮评价完整工作流程。</p>`:''}<p>期望值固定来自原始合成邮件，保存在宿主验证程序；Agent的输出不能自己给自己作答案。CLI查询确定编号和ID，再由独立管理员逐条读完整详情。</p>${parseSummary?`<p>验收选用的最后一次解析结果：${escape(JSON.stringify(parseSummary))}。首次及后续解析诊断都保留在CLI事件中；Agent须按来源复核、补齐后再预览，不能把最后一次结果当成首次自动解析表现。</p>`:""}<div class="table"><table><thead><tr><th>检查内容</th><th>原邮件要求</th><th>本轮结果</th></tr></thead><tbody>${fields.map(([name,value])=>`<tr><td>${name}</td><td>${value}</td><td>${fieldStatus}</td></tr>`).join('')}</tbody></table></div><p>${result.sopVersion==='sop-v3'?evidence('D2','contact-field-probe.json','单独的联系角色工程探测')+' · ':''}${evidence('D3','expected.json','原始期望')} · ${evidence('D2','preview.json','真实完整预览')} · ${evidence('D3','upload-result.json','真实导入回执')} · ${evidence('D3','admin-details-30.json','30条完整详情')} · ${evidence('D4','replay-result.json','新会话重放结果')}</p></section>
 <section><h2>5. 失败与恢复</h2><p>测试中主动制造拒绝授权、缺失信息、批准后变更、写入成功但回执丢失和确定失败。E1a、E1b是实际Pi场景；E1c～E1f混合实际Pi与宿主批准指纹、故障注入或真实CLI协议检查，各例分别标记。</p>${subcases.length?`<pre>${escape(JSON.stringify(subcases,null,2))}</pre>`:'本轮尚无完整负例记录。'}${history.length?`<h3>前几轮发现了什么</h3><p>历史失败全部保留。发现的问题包括：测试器误挡合法只读命令、重复添加全局参数、未授权时回读原值、只看缩减后的stdout、取消时跳过清理，以及Agent把访问授权当作业务批准。第三轮还确认了SOP样本已不符合现行online地址契约，且元数据CSV被误登记为整理文件；v2补了真实地图正例及缺地址负例。第四轮发现测试器把等价的连字符正则转义误判为失败，并暴露优先级规则dry-run未保存output文件；已修正断言并补齐CLI保存和回归覆盖。第五轮进一步发现自然语言诊断没有明确路由到auth.md，以及容器继承宿主loopback代理导致真实后端地图502；还发现模型凭据工具输出漏脱敏，自动门禁失败后已清除本地明文。下一轮补强诊断路由、地图直连与实际后端地图预检、已知密钥写证据前脱敏。第六轮已真实导入30条并逐条核对，也实际重放新增0；验收器却把already_imported计数当作布尔值，且独立管理员会话过期后没有续接，导致两个门禁失败。现已明确计数格式、补上仅一次只读会话续接，并避免重复截图导致的报告导出异常；历史结果不改为通过。第七轮歧义场景实际导入了用户补充后的100元/小时及周六14～16点，schema支持的hour却被只接受hourly的验收器误判；已依据当前schema和后端解析器同时接受这两个按小时单位，继续拒绝其它单位。同时发现Agent切入任务子目录时被执行器误挡，返回根目录后完成重放；现已支持物理子目录并补越界回归和真实相对文件检查。随后又发现通用整理指南已经20字段，邮件入口仍要求16字段，并把联系方式放备注；v3统一两份指南和完整示例为20字段，显式授课方式及独立联系列，同时增加不同用户/管理员电话的真实解析工程样本，避免指南之间继续冲突。第九轮第一次20字段实测又暴露真实Agent缺陷：解析器按规则给30条岗位优先级5，Agent重建ext时却丢掉priority，实际入库成为默认100。已保留解析、预览和完整详情对照，停止后续场景并完成清理；随后补清合并ext、保留解析业务优先级，并把逐行一致性检查提前到D2批准前。取消时还补了不再启动新Pi会话的检查。第十轮修复优先级后，30条预览全部保留5，实际导入created30/failed0，但模型在最终回复时请求超时，D3仍记失败。清理后仅恢复测试API作独立只读回查，证明30条全部字段及优先级5正确，未重启模型或重复写入；原始失败状态不改。随后启用Pi SDK原生有限模型重试（最多2次），保留已有工具历史、批准和幂等键，记录重试开始/结束，超预算仍失败。第十一轮准备失败是取证时Docker旧凭据挂载留下空目录，已确认空目录后仅清理专属临时路径，未开始业务测试。第十二轮A1～D4通过：实际30条全部字段和优先级5正确，重放新增0；恢复场景E1b、E1d被模型服务content_filter拒绝，E1e、E1f依赖未满足，原失败保留，不自动重试服务拒绝。清理本身成功，但长页截图导出错误令E2最终失败；网页实际两种宽度打开无溢出，截图调整为900高度的实际视口，并记录全文高度和页底访问，避免长图导出影响检查。对应修复记录在源码和历史证据中。</p>${history.map(h=>`<details><summary>${escape(h.runId)} · ${h.kind==='selected'?'专项':'完整'} / ${escape(h.sopVersion)} · ${labels[h.status]||escape(h.status)} · ${h.passed.length}项通过</summary><p>通过：${escape(h.passed.join('、'))}</p><pre>${escape(JSON.stringify(h.failed,null,2))}</pre><p>${escape(h.cancelled)}${h.manualCleanup?'；已另存手动清理记录。':''}</p>${link(h.result,'历史原始结果')}</details>`).join('')}`:''}</section>
 <section><h2>6. 回归、版本与结论</h2>${result.supplementary?.length?`<h3>追加验证</h3><ul>${result.supplementary.map(item=>`<li>${escape(item.summary)}；${link(path.join(output,item.path),'实际证据')}</li>`).join('')}</ul>`:''}${regressions.length?`<ul>${regressions.map(r=>`<li>${escape(r.name)}：${escape(r.state)}；${link(r.path,'实际日志')}</li>`).join('')}</ul>`:''}<p>HTML用Chromium在1440和390宽度实际打开，检查页面错误和横向溢出。${link(path.join(output,'render-check.json'),'浏览器检查结果')} · ${link(path.join(output,'report-1440.png'),'桌面截图')} · ${link(path.join(output,'report-390.png'),'手机截图')}。</p><p>后续所有编译使用job=1。早于该约束的后台镜像构建和后台Clippy使用过job=2；此处保留实际情况。</p><p>${result.status==='passed'&&full?'这轮固定版本、指定模型和这些样本达到了完整SOP标准。发现、授权、预览、业务确认、落库、独立回读、重放和各负例都有对应证据。':'本轮尚不能宣称完整SOP全部通过。通过条目只证明自己的范围；其它部分不能用旧轮次或静态回归代替。'}</p><p>范围：保存的合成邮件，不是接入真实邮箱；未覆盖全部26项能力的实际业务，也不证明其它模型都稳定。管理端使用既有固定镜像。Pi与宿主隔离，没有宿主历史、答案或Docker socket；同一容器中各任务目录并非安全隔离边界。</p><details><summary>同一容器及产品指纹</summary><pre>${escape(JSON.stringify(result.fingerprint,null,2))}</pre></details><details><summary>全部用例详细记录</summary>${result.cases.map(c=>`<h3>${escape(c.id)} ${escape(c.name)}</h3><pre>${escape(JSON.stringify(c,null,2))}</pre>`).join('')}</details></section>
 <section><h2>7. 下次怎么用</h2><p>进入cli/tests/agent-e2e，先构建当前版本，再执行统一入口：</p><pre>CARGO_BUILD_JOBS=1 cargo test --all-targets # 在cli目录执行Rust回归
npm run test:agent -- --mode docker --sop full
npm run test:agent -- --mode docker --sop selected --cases A3,B1 --preserve-run ${escape(result.runId)}
npm run test:report -- --run ${escape(result.runId)}</pre><p>完整轮次持锁后，只重建专属测试项目的hyacinthus_test。专项不reset，自动加入依赖并逐项重新执行。未选项保持未运行，不能称全量通过。</p><p>${link('/tmp/hyacinthus-shared-container-test-plan.html#sop','完整任务理解与标准操作卡')} · ${link('/home/r/Scripts/HyacinthusTotal/cli/tests/agent-e2e/SOP.md','仓库SOP')} · ${link('/home/r/Scripts/HyacinthusTotal/cli/tests/agent-e2e/cases/sop-v3.json','版本化执行清单')}</p><p>报告目录：${escape(output)}。本轮清理结果见E2。当前SOP停止Pi、移除使用复制地图密钥的API/Worker容器，并保留数据库等测试状态；专项恢复服务后复用同一Pi容器。旧轮次的清理按其实际记录说明。</p></section>
 </main></body></html>`;
}
/** Generate real desktop/mobile browser evidence for the archived result. */
export async function writeSopReport(output,result,{capture=true}={}){
 await mkdir(output,{recursive:true});const history=await historyBefore(output),regressions=await regressionEvidence(output);const html=renderSopHtml(result,{history,regressions,output});const file=path.join(output,'report.html');await writeFile(file,html);
 const checks=capture?[]:await optionalJson(path.join(output,'render-check.json'),[]);
 if(capture){const browser=await chromium.launch({headless:true,handleSIGINT:false,handleSIGTERM:false,handleSIGHUP:false});
 try{for(const width of [1440,390]){const page=await browser.newPage({viewport:{width,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`file://${file}`);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);const documentHeight=await page.evaluate(()=>document.documentElement.scrollHeight);await page.screenshot({path:path.join(output,`report-${width}.png`),fullPage:false});await page.evaluate(()=>scrollTo(0,document.documentElement.scrollHeight));checks.push({width,errors,overflow,documentHeight,screenshotMode:'viewport',bottomVisited:true});await page.close();}}finally{await browser.close();}}
 await writeFile(path.join(output,'render-check.json'),JSON.stringify(checks,null,2));if(capture||result.status==='passed')assert.ok(checks.length===2&&checks.every(c=>!c.overflow&&!c.errors.length),'HTML render acceptance failed');
 await writeFile('/tmp/hyacinthus-sop-latest.html',html.replaceAll('href="cases/',`href="${output}/cases/`).replaceAll('href="regressions/',`href="${output}/regressions/`).replace('href="result.json"',`href="${output}/result.json"`));return checks;
}
if(process.argv[1]&&path.resolve(process.argv[1])===import.meta.filename){const i=process.argv.indexOf('--run');if(i<0)throw new Error('Provide --run <run_id>');const output=path.join('/tmp/hyacinthus-sop-runs',path.basename(process.argv[i+1]));await writeSopReport(output,JSON.parse(await readFile(path.join(output,'result.json'),'utf8')));}
