// 改动说明：学校来源SOP v5逐例留证，并以宿主只读凭据边界、单次快照与实际容器挂载执行E2门禁，空结果按条件验收并在失败后继续清理。
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { readFile, writeFile, mkdir, readdir, unlink } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';
import { SOP_POLICY as P, sha, caseWorkspace } from './sop-policy.mjs';
import { containerCLI } from './container-broker.mjs';
import { contactFieldProbe } from './contact-fixture.mjs';
import { openPi, browserApprover } from './sop-session.mjs';
import { installCheck, upgradeCheck, offlineCheck, rootCommand, guardedDirectoryCheck } from './sop-engineering.mjs';
import { createAdminRequirementReader } from './admin-readback.mjs';
import { verifyNormalized, verifyReport, NORMALIZED_LABELS } from '../lib/verify.mjs';
import { sourceRows, mailFixture, normalizedLabelText, prefixRuleMatches, verifyReplayReport, verifyRunReuse } from './sop-verify.mjs';
import { redact, redactWithSecrets, POLICY as E2E_POLICY } from '../lib/policy.mjs';
import { verifyEmptySearch, cleanupSteps, safeChildOutput, captureChild, prepareSecrets } from './sop-lifecycle.mjs';
import { writeSopReport } from './sop-report.mjs';
import { recoveryCases } from './sop-recovery.mjs';
import { schoolQueryCase } from './sop-schools.mjs';
import { archiveTaskArtifacts } from './sop-artifacts.mjs';
import { mapEnvironment, probeMap, probeBackendMap, MAP_SECRET_KEYS, withoutMapSecrets } from './geo-fixture.mjs';
import { enterCredentialBoundary, captureCredentialSource, inspectCredentialIntegrity, readOnlyBoundary, verifyCredentialMounts, requireCredentialIntegrity } from './credential-boundary.mjs';
const hostCredentialPath=path.join(process.env.PI_CODING_AGENT_DIR||path.join(os.homedir(),'.pi/agent'),'auth.json');
const hostCredentialBoundary=await enterCredentialBoundary(hostCredentialPath,fileURLToPath(import.meta.url));
const repo=path.resolve(import.meta.dirname,'../../../..');
const base=path.join(repo,'.tmp/e2e/skills-alignment');
const spec=JSON.parse(await readFile(path.join(import.meta.dirname,'../cases/sop-v5.json'),'utf8'));
assert.deepEqual(spec.fixture.normalized_labels,NORMALIZED_LABELS,'SOP labels differ from the published validator');
const args=process.argv.slice(2);
/** Read one execution option without using shell expansion. */
function option(key,fallback){const i=args.indexOf(key);return i<0?fallback:args[i+1];}
const mode=option('--mode','docker');assert.equal(mode,'docker','Use test:agent:host for the separately labelled host diagnostic');
const kind=option('--sop','full');assert.ok(['full','selected'].includes(kind));
const preserveRun=option('--preserve-run','');if(preserveRun){assert.equal(kind,'selected');assert.match(preserveRun,/^SOP\d+$/);}
const selected=new Set(kind==='full'?spec.cases.map(c=>c.id):(option('--cases','')).split(',').filter(Boolean));
assert.ok(selected.size);for(const id of selected)assert.ok(spec.cases.some(c=>c.id===id),`Unknown SOP case ${id}`);
for(const id of [...selected]) { const add=id=>{const c=spec.cases.find(c=>c.id===id);for(const dependency of c.dependsOn){selected.add(dependency);add(dependency);}};add(id); }
selected.add('E2');
const runId=`SOP${Date.now()}`;
const output=path.join('/tmp/hyacinthus-sop-runs',runId);
const workspace=path.join(base,'workspace');
const credentialSnapshotPath=path.join(base,'private/mimo-auth.json');
const result={runId,sopVersion:spec.version,specPath:"cases/sop-v5.json",fixture:spec.fixture,kind,startedAt:new Date().toISOString(),model:'xiaomi-token-plan-cn/mimo-v2.6-pro',policy:P,cases:spec.cases.map(c=>({...c,status:'not_run'})),assumptions:['保存的合成邮件，不接入邮箱','API/Worker/CLI为当前源码；管理端为固定既有镜像','所有真实Pi与CLI执行共用唯一Pi容器']};
const sessions=new Set();const profiles=new Set();let approver,adminRead,mailPi,fixture,beforeIds,firstHashes,globalFingerprint;
let locked=false;let sensitive=[];let cancelled=false;let credentialBaseline,containerCredentialBoundary,preparationProcess;
/** Stop new business cases on cancellation while retaining report and cleanup work. */
function cancel(){cancelled=true;for(const pi of sessions)pi.cancel();}
process.on('SIGINT',cancel);process.on('SIGTERM',cancel);
const suiteTimer=setTimeout(cancel,P.suiteMs);
/** Keep each batch report up to date, including failures and unexecuted dependent cases. */
async function persist(){await mkdir(output,{recursive:true});await writeFile(path.join(output,'result.json'),JSON.stringify(redact(result),null,2));for(const entry of result.cases){await mkdir(path.join(output,'cases',entry.id),{recursive:true});await writeFile(path.join(output,'cases',entry.id,'case.json'),JSON.stringify(redact(entry),null,2));}}
/** Scan every public text artifact, including model event streams and the generated report. */
async function scanPublicEvidence(root){let files=0;for(const entry of await readdir(root,{withFileTypes:true})){const file=path.join(root,entry.name);if(entry.isDirectory())files+=await scanPublicEvidence(file);else if(/\.(json|ndjson|log|html|txt|csv|md)$/.test(entry.name)){const content=await readFile(file,'utf8');assert.ok(sensitive.every(value=>!value||!content.includes(value)),'A secret entered public evidence');assert.ok(!/(?:用户代码|用户码|授权码|user[ _-]*code)[：:\s*`]*[A-Z0-9]{4}-[A-Z0-9]{4}/i.test(content),'An authorization code entered public evidence');assert.ok(!/https?:\/\/[^\s"<>]+\/admin\/agent-auth\/authorize[^\s"<>]*user_code=/i.test(content),'An original authorization URL entered public evidence');files++;}}return files;}
/** Capture preparation diagnostics using only task-private redaction inputs; publish after cleanup. */
async function child(command,argv){
 const captured=await captureChild(command,argv,{maxOutputBytes:E2E_POLICY.maxOutputBytes});
 try{sensitive.push(...await prepareSecrets(path.join(base,'private'),MAP_SECRET_KEYS));preparationProcess=redactWithSecrets(captured,sensitive);}
 catch(error){preparationProcess={exitCode:captured.exitCode,signal:captured.signal,stdout:'<withheld: redaction inputs unavailable>',stderr:'<withheld: redaction inputs unavailable>',redactionError:safeChildOutput(error.message)};throw new Error('Preparation diagnostics could not be safely redacted');}
 if(captured.spawnError||captured.exitCode!==0)throw new Error(`${path.basename(command)} exited ${captured.exitCode ?? captured.signal ?? 'spawn-error'}`);
}
/** Enumerate only this acceptance project's containers, distinguishing absence from Docker errors. */
function projectContainerNames(){return execFileSync('docker',['ps','-a','--filter',`label=com.docker.compose.project=${P.project}`,'--format','{{.Names}}'],{encoding:'utf8'}).trim().split('\n').filter(Boolean);}
/** Remove one credential-bearing service without requiring a generated Compose env file. */
function removeCredentialService(service){const ids=execFileSync('docker',['ps','-a','--filter',`label=com.docker.compose.project=${P.project}`,'--filter',`label=com.docker.compose.service=${service}`,'--format','{{.ID}}'],{encoding:'utf8'}).trim().split('\n').filter(Boolean);if(ids.length)execFileSync('docker',['rm','-f',...ids],{stdio:'ignore',timeout:30_000});return {service,removed:ids.length,absent:ids.length===0};}
/** Wait for the real test database marker and Worker readiness after either full setup or selected service restoration. */
async function waitReadyStack(){for(let attempt=0;attempt<60;attempt++){try{const ready=await fetch(`${P.api}/health/ready`);const worker=execFileSync('docker',['logs',`${P.project}-worker-1`],{encoding:'utf8',stdio:['ignore','pipe','pipe']});if(ready.status===200&&ready.headers.get('x-hyacinthus-test-database')==='hyacinthus_test'&&worker.includes('worker runtime started'))return;}catch{}await new Promise(resolve=>setTimeout(resolve,500));}throw new Error('Test API/database marker and Worker did not become ready');}
/** Capture the immutable shared container and installed product fingerprints. */
function fingerprint(){const info=JSON.parse(execFileSync('docker',['inspect','--format','{{json .}}',P.container],{encoding:'utf8'}));const skills=rootCommand(['python3','-c',"import pathlib,hashlib,json;root=pathlib.Path('/home/node/.pi/agent/skills');print(json.dumps({str(p.relative_to(root)):hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(root.rglob('*')) if p.is_file()}))"]);
 return {container_id:info.Id,image_id:info.Image,cli_hash:rootCommand(['sha256sum',P.binary]).split(' ')[0],skills_hash:sha(skills),skills:JSON.parse(skills),pi_version:rootCommand(['node','-e',"console.log(require('/usr/local/lib/node_modules/@earendil-works/pi-coding-agent/package.json').version)"]).trim()};}
/** Record immutable service image IDs and mount boundaries without reading secret environments. */
function environmentManifest(){const names=execFileSync('docker',['ps','-a','--filter',`label=com.docker.compose.project=${P.project}`,'--format','{{.Names}}'],{encoding:'utf8'}).trim().split('\n').filter(Boolean);const containers=names.map(name=>JSON.parse(execFileSync('docker',['inspect','--format','{{json .}}',name],{encoding:'utf8'})));containerCredentialBoundary=verifyCredentialMounts(containers,P.container,credentialSnapshotPath,hostCredentialBoundary.directories.map(item=>item.directory));return {capturedAt:new Date().toISOString(),credentialBoundary:containerCredentialBoundary,containers:containers.map(d=>({name:d.Name.slice(1),id:d.Id,image:d.Config.Image,image_id:d.Image,state:d.State.Status,user:d.Config.User,mounts:d.Mounts.map(m=>({type:m.Type,destination:m.Destination,readOnly:!m.RW})),dockerSocketMounted:d.Mounts.some(m=>m.Destination.includes('docker.sock'))}))};}
/** Write evidence into the current case's standardized host directory. */
async function evidence(id,name,value){const dir=path.join(output,'cases',id);await mkdir(dir,{recursive:true});await writeFile(path.join(dir,name),JSON.stringify(redact(value),null,2));return `cases/${id}/${name}`;}
/** Create a genuinely new model conversation while preserving only explicitly chosen task state. */
async function session(id,{profile=id,folder=id,api,scopes,evidenceSuffix,networkDenied=false}={}){assert.ok(!cancelled,'Suite cancelled: do not open another Pi session');const def=spec.cases.find(c=>c.id===id)||spec.cases.find(c=>c.id==='D1');const profileName=`${runId}-${profile}`;const initialized=profiles.has(profileName);profiles.add(profileName);const control={caseId:id,profile:profileName,...caseWorkspace(workspace,runId,folder),evidence:path.join(output,'cases',id.startsWith('E1')&&id!=='E1'?'E1':id,...(id.startsWith('E1')&&id!=='E1'?[id]:evidenceSuffix?[evidenceSuffix]:[])),scopes:scopes||def.scopes||[],api,networkDenied};
 await mkdir(control.workspace,{recursive:true});await mkdir(control.evidence,{recursive:true});if(!initialized){const setup=await containerCLI(control,['config','set-profile',profileName,'--base-url',control.api||'http://backend:8000','--client-type','pi','--client-instance-id',profileName,'--client-display-name','Pi SOP']);assert.equal(setup.exitCode,0,setup.stderr);}
 const pi=await openPi(control,approver,{secrets:sensitive});sessions.add(pi);return pi;}
/** End one conversation without changing the container or its installed product. */
async function close(pi){await pi.close();sessions.delete(pi);await archiveTaskArtifacts(pi.control.workspace,pi.control.evidence);}
/** Obtain a successful actual CLI envelope using a case's existing authorization. */
async function readCLI(pi,argv){const response=await containerCLI(pi.control,argv);assert.equal(response.exitCode,0,response.stderr);const value=JSON.parse(response.stdout);assert.equal(value.ok,true,JSON.stringify(value.error));return value.data;}
/** Find one identity-bound Agent artifact, never accepting a stale file from another mail run. */
async function findArtifact(name,root=mailPi.control.workspace){for(const entry of await readdir(root,{withFileTypes:true})){if(entry.isDirectory()&&!entry.name.startsWith('.')){const found=await findArtifact(name,path.join(root,entry.name));if(found)return found;}else if(entry.name===name){const file=path.join(root,name);const data=JSON.parse(await readFile(file,'utf8'));if(data.message_id===fixture.messageId||data.source_message_id===fixture.messageId)return {file,data};}}}
/** Check each source number's persisted identity and read full fields from an independent host-only administrator. */
async function details(pi){const values=[];for(const expected of fixture.expected){const d=await readCLI(pi,['requirements','search','--keyword',expected.code,'--scope','all']);const matches=d.items.filter(r=>r.requirement_code===expected.code);assert.equal(matches.length,1);values.push(await adminRead(matches[0].id));}return values;}
/** Run one case, preserve its first failure, and continue only independent cases. */
async function run(id,fn){const entry=result.cases.find(c=>c.id===id);if(!selected.has(id))return;if(cancelled&&id!=='E2'){entry.status='blocked';entry.reason='Suite cancelled or total time budget exceeded';await persist();return;}
 const missing=entry.dependsOn.filter(d=>result.cases.find(c=>c.id===d).status!=='passed');if(missing.length){entry.status='blocked';entry.reason=`Dependencies not passed: ${missing.join(',')}`;await persist();return;}
 entry.startedAt=new Date().toISOString();try{if(id!=='E2'){const current=fingerprint();assert.equal(current.container_id,globalFingerprint.container_id);assert.equal(current.cli_hash,globalFingerprint.cli_hash);assert.equal(current.skills_hash,globalFingerprint.skills_hash);Object.assign(entry,current);}
 const actual=await fn();if(id!=='E2'){const after=fingerprint();assert.equal(after.container_id,globalFingerprint.container_id);assert.equal(after.cli_hash,globalFingerprint.cli_hash);assert.equal(after.skills_hash,globalFingerprint.skills_hash);}entry.actual=actual;entry.status='passed';}catch(e){entry.status='failed';entry.reason=redact(e.message);if(id==='E1'){try{entry.actual={subcases:JSON.parse(await readFile(path.join(output,'cases/E1/subcases.json'),'utf8'))};}catch{}}entry.error_category=/approval|Agent|Pi did|source|Wrong|Missing|duplicate/i.test(e.message)?'agent':/fetch|timeout|model|exited/i.test(e.message)?'infra':'harness';console.error(`${id}: ${entry.reason}`);}
 entry.endedAt=new Date().toISOString();entry.duration_ms=Date.parse(entry.endedAt)-Date.parse(entry.startedAt);await evidence(id,'case.json',entry);await persist();console.log(`${id} ${entry.status} (${Math.round(entry.duration_ms/1000)}s)`);}
try{
 await mkdir(output,{recursive:true});await writeFile(path.join(output,'sop-spec.json'),JSON.stringify(spec,null,2));const lock=path.join(base,'sop.lock');await mkdir(base,{recursive:true});
 try{const previous=JSON.parse(await readFile(lock,'utf8'));try{process.kill(previous.pid,0);throw new Error(`SOP environment owned by PID ${previous.pid}`);}catch(e){if(e.code!=='ESRCH')throw e;await unlink(lock);}}catch(e){if(e.code!=='ENOENT')throw e;}
 await writeFile(lock,JSON.stringify({pid:process.pid,runId}),{flag:'wx',mode:0o600});locked=true;
 credentialBaseline=await captureCredentialSource(hostCredentialPath,credentialSnapshotPath);
 await evidence('E2','credential-baseline.json',{...credentialBaseline,hostBoundary:hostCredentialBoundary});
 if(kind==='full')await child(process.execPath,[path.join(import.meta.dirname,'prepare.mjs'),'--credential-snapshot',credentialSnapshotPath]);
 else {const geo=await mapEnvironment(repo);const env=path.join(base,'private/backend.env');await writeFile(env,withoutMapSecrets(await readFile(env,'utf8'))+'\n'+Object.entries(geo).filter(([key])=>MAP_SECRET_KEYS.includes(key)).map(([key,value])=>`${key}=${value}`).join('\n')+'\n',{mode:0o600});execFileSync('docker',['compose','--env-file',path.join(base,'compose.env'),'-p',P.project,'-f',path.join(import.meta.dirname,'compose.yml'),'up','-d','backend','worker'],{stdio:'ignore'});execFileSync('docker',['start',P.container],{stdio:'ignore'});}
 await waitReadyStack();
 await writeFile(path.join(output,'backend-map-probe.json'),JSON.stringify(await probeBackendMap(P.api),null,2));
 const password=(await readFile(path.join(base,'private/driver.env'),'utf8')).trim().slice('HYACINTHUS_E2E_ADMIN_PASSWORD='.length);sensitive.push(password);const modelAuth=JSON.parse(await readFile(path.join(base,'private/mimo-auth.json'),'utf8'));sensitive.push(modelAuth['xiaomi-token-plan-cn'].key);const geoConfig=await mapEnvironment(repo);sensitive.push(...MAP_SECRET_KEYS.map(key=>geoConfig[key]));await writeFile(path.join(output,'real-map-probe.json'),JSON.stringify(await probeMap(geoConfig),null,2));approver=browserApprover(password);adminRead=createAdminRequirementReader({api:P.api,admin:P.admin,password});
 globalFingerprint=fingerprint();result.fingerprint=globalFingerprint;await writeFile(path.join(output,'environment.json'),JSON.stringify(environmentManifest(),null,2));await writeFile(path.join(output,'run.json'),JSON.stringify(result,null,2));
 if(preserveRun){const previousOutput=path.join('/tmp/hyacinthus-sop-runs',preserveRun);const previous=JSON.parse(await readFile(path.join(previousOutput,'result.json'),'utf8'));assert.equal(previous.sopVersion,spec.version,'Reuse requires the same SOP version');const original=JSON.parse(await readFile(path.join(previousOutput,'cases/D3/admin-details-30.json'),'utf8'));const expected=JSON.parse(await readFile(path.join(previousOutput,'cases/D3/expected.json'),'utf8'));const current=[];for(const row of original)current.push(await adminRead(row.id));const reused=verifyRunReuse(previous,globalFingerprint,original,current,expected);await writeFile(path.join(output,'same-container-reuse.json'),JSON.stringify(reused,null,2));await writeFile(path.join(output,'preserved-admin-details-30.json'),JSON.stringify(current,null,2));result.supplementary=[{path:'same-container-reuse.json',summary:`复用完整轮次${preserveRun}的同一容器、镜像、CLI和Skills，30条既有岗位ID、创建时间及完整业务字段保持一致`}];}
 fixture=mailFixture(runId);await evidence('D1','source-manifest.json',{message_id:fixture.messageId,sha256:sha(fixture.mail),rows:fixture.expected.length});await evidence('D3','expected.json',fixture.expected);
 await run('A1',async()=>{const data=installCheck();await evidence('A1','installer.json',data);return {paths:3,roots:2,references:11,releaseDownloadTested:false};});
 await run('A2',async()=>{const data=upgradeCheck();await evidence('A2','upgrade.json',data);return {legacyFixtureUpgrade:true,customFilesPreserved:true,damageDetected:true};});
 await run('A3',async()=>{const data=offlineCheck();await evidence('A3','offline.json',data);const control={caseId:'A3',profile:`${runId}-directory`,...caseWorkspace(workspace,runId,'A3-directory'),evidence:path.join(output,'cases/A3'),scopes:[]};const nested=await guardedDirectoryCheck(control);await evidence('A3','nested-directory.json',nested);return {environments:3,socketSyscallsActuallyDenied:true,readFiles:13,nestedRelativeFiles:nested};});
 await run('B1',async()=>{const pi=await session('B1');try{const reply=await pi.task(spec.cases.find(c=>c.id==='B1').prompt);assert.deepEqual(pi.discovery.skills.map(s=>s.name).sort(),['hyacinthus-cli','tutoring-job-mail-upload']);assert.equal(pi.discovery.retryPolicy.enabled,true);assert.equal(pi.discovery.retryPolicy.maxRetries,2);assert.ok(pi.tools.some(t=>t.detail?.type==='tool_execution_start'&&t.detail.toolName==='read'&&t.detail.args.path.endsWith('/hyacinthus-cli/SKILL.md')),'Agent did not read discovered entry');assert.match(reply.text,/需求|岗位/);return {session_id:pi.discovery.sessionId,normalDiscovery:true};}finally{await close(pi);}});
 await run('B2',async()=>{const pi=await session('B2');try{await pi.task(spec.cases.find(c=>c.id==='B2').prompt);let healthy=pi.broker.events.findLast(e=>e.action==='doctor'&&e.result?.ok&&e.result.data.checks.every(c=>c.status!=='fail'));
 if(!healthy){await pi.task('可以，请通过正常授权完成检查，申请本次检查所需的最小权限。');healthy=pi.broker.events.findLast(e=>e.action==='doctor'&&e.result?.ok&&e.result.data.checks.every(c=>c.status!=='fail'));}
 assert.ok(healthy,'No successful real doctor check');assert.ok(healthy.result.data.checks.every(c=>c.status!=='fail'));assert.ok(healthy.argv.includes('--strict'));
 const bad=await session('B2',{profile:'B2',folder:'B2-unavailable',evidenceSuffix:'unavailable',networkDenied:true});try{await bad.task('帮我检查当前测试实例是否可用，把发现的问题告诉我。');const failed=bad.broker.events.findLast(e=>e.action==='doctor'&&e.exitCode!==0);assert.ok(failed,'Network diagnosis omitted doctor --strict with a nonzero result');const checks=failed.result?.error?.detail?.checks;assert.equal(checks?.find(c=>c.name==='token_present')?.status,'pass','Network negative must retain valid authorization');assert.equal(checks?.find(c=>c.name==='capability_endpoint')?.status,'fail');assert.ok(!bad.broker.events.some(e=>e.writes));await evidence('B2','negative-events.json',bad.broker.events);}finally{await close(bad);}return {healthy:true,negativeStopsWrites:true,negativeKeepsValidToken:true,realNetworkSyscallsDenied:true,session_id:pi.discovery.sessionId};}finally{await close(pi);}});
 await run('B3',async()=>{const pi=await session('B3');try{await pi.task(spec.cases.find(c=>c.id==='B3').prompt);return {session_id:pi.discovery.sessionId,...verifyEmptySearch(pi.broker.events,{keywords:['数学','初一']})};}finally{await close(pi);}});
 await run('C1',async()=>{const pi=await session('C1');try{const def=spec.cases.find(c=>c.id==='C1');await pi.task(def.prompt.replaceAll('{run_id}',runId));const before=await adminRead.currentUser();await evidence('C1','before.json',before);assert.notEqual(before.display_name,`SOP-${runId}`);await pi.approve(def.approval.replaceAll('{run_id}',runId));const after=await readCLI(pi,['user','me']);assert.equal(after.display_name,`SOP-${runId}`);await evidence('C1','after.json',after);return {session_id:pi.discovery.sessionId,previewBoundToWrite:true,actualName:after.display_name};}finally{await close(pi);}});
 await run('C2',async()=>{const pi=await session('C2');try{const def=spec.cases.find(c=>c.id==='C2');await pi.task(def.prompt.replaceAll('{run_id}',runId));const before=await adminRead.rules();assert.ok(!before.some(r=>r.pattern.includes(runId)));await evidence('C2','before.json',before);await pi.approve(def.approval);const after=await readCLI(pi,['requirements','priority-rules','list']);const rules=after.filter(r=>prefixRuleMatches(r,runId));assert.equal(rules.length,1);assert.equal(rules[0].priority,5);await evidence('C2','after.json',rules);return {session_id:pi.discovery.sessionId,rule:rules[0],matchValidation:'D3'};}finally{await close(pi);}});
 await run('C3',async()=>schoolQueryCase({definition:spec.cases.find(c=>c.id==='C3'),session,close,readCLI,evidence,runId}));
 await run('D1',async()=>{mailPi=await session('D1',{folder:'mail',profile:'mail'});const def=spec.cases.find(c=>c.id==='D1');const missingSource=await mailPi.task(def.prompt);assert.match(missingSource.text,/请|需要|提供|哪|路径|原文/,'Agent did not ask for the missing mail source');assert.match(missingSource.text,/邮件|邮箱|来源|路径|文件|原文/);assert.ok(!mailPi.broker.events.some(e=>e.writes||e.action==='auth login'||e.action==='requirements parse'),'Agent advanced the upload before receiving a mail source');await evidence('D1','missing-source.json',{asked:true,reply:missingSource.text,toolCalls:mailPi.tools.filter(t=>t.detail?.type==='tool_execution_start').length});await writeFile(path.join(mailPi.control.workspace,'saved_mail.txt'),fixture.mail);await mailPi.task(def.sourceReply);
 const artifact=await findArtifact('mail_manifest.json');assert.ok(artifact,'Missing mail manifest');const root=path.dirname(artifact.file);const raw=await readFile(path.resolve(root,artifact.data.raw_file));assert.equal(raw.toString(),fixture.mail);assert.equal(artifact.data.source_sha256,sha(raw));assert.ok(!path.isAbsolute(artifact.data.raw_file)&&!artifact.data.raw_file.split('/').includes('..'));
 const texts=[];for(const name of artifact.data.normalized_files){assert.ok(!path.isAbsolute(name)&&!name.split('/').includes('..'));texts.push(normalizedLabelText(name,await readFile(path.join(root,name),'utf8')));}verifyNormalized(texts.join('\n\n'),fixture.expected);await evidence('D1','manifest.json',artifact.data);return {session_id:mailPi.discovery.sessionId,rows:30,sourceBytesPreserved:true,all21LabelsVerified:true};});
 await run('D2',async()=>{const parse=mailPi.broker.events.findLast(e=>e.action==='requirements parse'&&e.result?.data?.rows);assert.ok(parse,'No real parser result');assert.equal(parse.result.data.rows.length,30);const preview=mailPi.broker.events.findLast(e=>e.action==='requirements import'&&e.preview);assert.ok(preview,'No actual full dry-run preview');sourceRows(preview.preview.request.body.confirmed_rows,fixture.expected,{parsedRows:parse.result.data.rows.map(row=>row.parsed)});assert.ok(!mailPi.broker.events.some(e=>e.writes));const workerLog=execFileSync('docker',['logs','--since',result.cases.find(c=>c.id==='D1').startedAt,`${P.project}-worker-1`],{encoding:'utf8',maxBuffer:8*1024*1024}).replace(/\x1b\[[0-9;]*m/g,'');const completions=workerLog.split('\n').filter(line=>line.includes('kind="requirement_parse"')&&line.includes('status=Succeeded'));assert.ok(completions.length,'No real Worker parse completion recorded');const jobId=parse.result.meta?.job_id;if(jobId)assert.ok(completions.some(line=>line.includes(jobId)),'CLI parse job did not match Worker completion');await evidence('D2','worker-parse.json',{jobId:jobId||null,correlation:jobId?'job-id':'case-time-window',completed:completions});const parserAttempts=mailPi.broker.events.filter(e=>e.action==='requirements parse'&&e.result?.data?.rows).map(e=>({at:e.at,summary:e.result.data.summary,errorCodes:[...new Set(e.result.data.rows.flatMap(r=>r.errors||[]))]}));await evidence('D2','parser-attempts.json',parserAttempts);const contactProbe=await contactFieldProbe(mailPi.control,runId);await evidence('D2','contact-field-probe.json',contactProbe);await evidence('D2','parsed.json',parse.result);await evidence('D2','preview.json',preview.preview);return {rows:30,parserOriginalSummary:parse.result.data.summary,parserAttempts,realWorkerParse:true,contactRoleEngineeringProbe:true,workerCompletionEvidence:true,workerCorrelation:jobId?'job-id':'case-time-window',completePreviewFileOrEnvelope:true,sourceFieldsMatched:true};});
 await run('D3',async()=>{for(const e of fixture.expected){const d=await readCLI(mailPi,['requirements','search','--keyword',e.code,'--scope','all']);assert.equal(d.total,0);}await evidence('D3','before-counts.json',{rows:0});await mailPi.approve(spec.cases.find(c=>c.id==='D3').approval);
 const receipt=mailPi.broker.events.find(e=>e.writes&&e.result?.ok)?.result?.data;assert.ok(receipt);assert.equal(receipt.created,30);assert.equal(receipt.updated,0);assert.equal(receipt.failed,0);
 const items=await details(mailPi);await evidence('D3','admin-details-30.json',items);sourceRows(items,fixture.expected,{persisted:true});beforeIds=items.map(r=>r.id);await evidence('D3','upload-result.json',receipt);
 const final=await findArtifact('final_report.json');assert.ok(final);verifyReport(final.data,fixture.expected.map(e=>e.code),receipt,fixture.messageId);firstHashes={file:final.file,hash:sha(await readFile(final.file))};await evidence('D3','final-report.json',final.data);
 const reads=mailPi.broker.events.filter(e=>e.action==='requirements search'&&e.result?.ok).flatMap(e=>e.result.data.items.map(r=>r.requirement_code));assert.ok(fixture.expected.every(e=>reads.includes(e.code)),'Agent did not read back every code');await close(mailPi);return {rows:30,created:30,failed:0,allSourceFieldsMatched:true,priorityMatched:30,ids:beforeIds};});
 await run('D4',async()=>{const pi=await session('D4',{folder:'mail',profile:'mail'});try{mailPi=pi;await pi.task(spec.cases.find(c=>c.id==='D4').prompt);const replay=await findArtifact('replay_report.json');assert.ok(replay);verifyReplayReport(replay.data,fixture.messageId,fixture.expected.length);assert.ok(!pi.broker.events.some(e=>e.writes),'Replay attempted an unapproved write');const items=await details(pi);assert.deepEqual(items.map(r=>r.id),beforeIds);assert.equal(sha(await readFile(firstHashes.file)),firstHashes.hash);await evidence('D4','replay-result.json',replay.data);await evidence('D4','after-ids.json',items.map(r=>r.id));return {session_id:pi.discovery.sessionId,newCreated:0,preservedIds:30,originalReportPreserved:true};}finally{await close(pi);}});
 await run('E1',async()=>recoveryCases({session,close,readCLI,evidence,runId,fixture,adminRead}));
}catch(e){result.failure=redact(e.message);console.error(result.failure);for(const c of result.cases)if(selected.has(c.id)&&c.status==='not_run'&&c.id!=='E2'){c.status='blocked';c.reason=result.failure;}}
finally{
 clearTimeout(suiteTimer);
 for(const pi of sessions)await close(pi).catch(e=>{result.sessionCleanupError=redact(e.message);});if(approver)await approver.close().catch(e=>{result.approverCleanupError=redact(e.message);});
 if(locked){await run('E2',async()=>{
 const revocations=[];let integrity,finalHostBoundary,finalContainerBoundary,piStopped=false,piAbsent=false;
 const initialContainerBoundary=containerCredentialBoundary;
 const steps=await cleanupSteps([
  ...[...profiles].map(profile=>({name:`revoke:${profile}`,run:async()=>{const control={profile,cwd:'/workspace'};const initial=await containerCLI(control,['auth','status']);assert.equal(initial.exitCode,0,'Profile status failed');const state=JSON.parse(initial.stdout);if(!state.data?.token_present){const local=await containerCLI(control,['auth','logout','--local-only']);assert.equal(local.exitCode,0,'Unauthenticated pending-state cleanup failed');revocations.push({profile,noGrant:true,pendingStateCleared:true,localOnly:true});return;}const r=await containerCLI(control,['auth','logout']);assert.equal(r.exitCode,0,'Profile revocation failed');assert.equal(JSON.parse(r.stdout).ok,true);const status=await containerCLI(control,['auth','status']);assert.equal(status.exitCode,0,'Revocation readback failed');assert.ok(!JSON.parse(status.stdout).data?.token_present,'Revoked profile still has token');revocations.push({profile,exitCode:r.exitCode,ok:true});}})),
  {name:'revocation-evidence',run:()=>evidence('E2','revocations.json',revocations)},
  {name:'stop-pi',run:()=>{if(!projectContainerNames().includes(P.container)){piAbsent=true;return {absent:true};}execFileSync('docker',['stop',P.container],{stdio:'ignore',timeout:30_000});piStopped=true;return {stopped:true};}},
  {name:'credential-integrity',run:async()=>{integrity=await inspectCredentialIntegrity(credentialBaseline,hostCredentialPath,credentialSnapshotPath);return integrity;}},
  {name:'host-boundary',run:()=>{finalHostBoundary=readOnlyBoundary(hostCredentialBoundary.directories.map(item=>item.directory));return finalHostBoundary;}},
  {name:'container-boundary',run:()=>{finalContainerBoundary=environmentManifest().credentialBoundary;return finalContainerBoundary;}},
  {name:'integrity-evidence',run:()=>evidence('E2','host-credential-integrity.json',{...integrity,hostBoundary:finalHostBoundary,containerBoundary:finalContainerBoundary})},
  {name:'delete-model-snapshot',run:async()=>{try{await unlink(credentialSnapshotPath);return {deleted:true};}catch(error){if(error.code!=='ENOENT')throw error;return {alreadyAbsent:true};}}},
  {name:'remove-backend',run:()=>removeCredentialService('backend')},
  {name:'remove-worker',run:()=>removeCredentialService('worker')},
  {name:'clean-map-env',run:async()=>{const file=path.join(base,'private/backend.env');let content;try{content=await readFile(file,'utf8');}catch(error){if(error.code==='ENOENT')return {alreadyAbsent:true};throw error;}await writeFile(file,withoutMapSecrets(content),{mode:0o600});return {copiedFieldsRemoved:MAP_SECRET_KEYS};}},
  ...(preparationProcess?[{name:'prepare-output-evidence',run:()=>evidence('E2','prepare-process.json',preparationProcess)}]:[]),
  {name:'closed-sessions',run:()=>assert.ok(!result.sessionCleanupError&&!result.approverCleanupError,'Session or browser cleanup failed')},
  {name:'isolation-gate',run:()=>{requireCredentialIntegrity(integrity??{},finalHostBoundary,initialContainerBoundary);requireCredentialIntegrity(integrity??{},finalHostBoundary,finalContainerBoundary);}},
  {name:'public-evidence-scan',run:async()=>{const files=await scanPublicEvidence(output);await evidence('E2','redaction-check.json',{files,knownSecretMatches:0});return {files,knownSecretMatches:0};}},
 ],value=>redactWithSecrets(safeChildOutput(value),sensitive));
 const cleanup={steps,profiles:profiles.size,revocations:revocations.length,piStopped,piAbsent,
  temporaryModelCredentialDeleted:steps.find(step=>step.name==='delete-model-snapshot')?.status==='passed',
  temporaryMapCredentialsRemoved:steps.filter(step=>['remove-backend','remove-worker','clean-map-env'].includes(step.name)).every(step=>step.status==='passed'),
  hostCredentialDirectoryReadOnly:!!finalHostBoundary,originalCredentialMounted:finalContainerBoundary?.originalCredentialMounted,
  selectedProviderUnchanged:integrity?.selectedProviderUnchanged??false,privateSnapshotUnchanged:integrity?.snapshotUnchanged??false,
  hostWholeFileUnchanged:integrity?.hostObservation?.wholeFileUnchanged,otherProviderChanges:integrity?.hostObservation?.changedProviders};
 try{await evidence('E2','map-credential-cleanup.json',{steps:steps.filter(step=>['remove-backend','remove-worker','clean-map-env'].includes(step.name)),sourceConfigurationWritten:false,temporaryCopiesRemoved:cleanup.temporaryMapCredentialsRemoved});}catch(error){steps.push({name:'map-cleanup-evidence',status:'failed',error:redactWithSecrets(safeChildOutput(error.message),sensitive)});}
 result.cases.find(entry=>entry.id==='E2').actual=cleanup;await evidence('E2','cleanup-steps.json',cleanup);
 const failed=steps.filter(step=>step.status==='failed');assert.equal(failed.length,0,`E2 cleanup or proof failed: ${failed.map(step=>step.name).join(', ')}`);return cleanup;
 });await unlink(path.join(base,'sop.lock')).catch(()=>{});}

 result.endedAt=new Date().toISOString();result.durationMs=Date.parse(result.endedAt)-Date.parse(result.startedAt);result.status=result.failure||result.cases.some(c=>selected.has(c.id)&&c.status!=='passed')?'failed':'passed';
 await persist();try{const checks=await writeSopReport(output,result);const files=await scanPublicEvidence(output);const cleanup=result.cases.find(c=>c.id==='E2');cleanup.actual={...cleanup.actual,renderChecks:checks,publicTextFiles:files};await evidence('E2','redaction-check.json',{files,knownSecretMatches:0,includesGeneratedReport:true,includesModelEventStreams:true});}catch(error){const cleanup=result.cases.find(c=>c.id==='E2');cleanup.status='failed';cleanup.reason=redact(error.message);result.status='failed';result.reportError=cleanup.reason;}
 await persist();await writeSopReport(output,result,{capture:false});console.log(`SOP ${result.status}: ${output}/report.html`);if(result.status!=='passed')process.exitCode=1;
}
